import time
from urllib.parse import quote
from pyrogram import filters
from DAXXMUSIC import app


@app.on_message(filters.command("generate"))
async def generate_image(_, message):
    if len(message.command) < 2:
        return await message.reply_text("🖼️ Usage: /generate a futuristic city")

    prompt = message.text.split(None, 1)[1]
    wait = await message.reply_text("🎨 Generating image, please wait...")

    start = time.time()

    # FREE AI image generator
    image_url = f"https://image.pollinations.ai/prompt/{quote(prompt)}"

    try:
        await wait.delete()
        await message.reply_photo(
            photo=image_url,
            caption=(
                f"🖼️ Prompt: `{prompt}`\n"
                f"⏱️ Time: {round(time.time() - start, 2)}s\n\n"
                f"✨ Generated by @kira_probot"
            )
        )
    except Exception as e:
        await wait.edit_text(f"❌ Image generation failed: {type(e).__name__}")
