import random
from pyrogram import filters, enums
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton
from DAXXMUSIC import app

PASSWORD_CACHE = {}


@app.on_message(filters.command(["genpassword", "genpass"]))
async def password(bot, update):
    message = await update.reply_text("Pʀᴏᴄᴇꜱꜱɪɴɢ...")

    chars = "abcdefghijklmnopqrstuvwxyz1234567890!@#$%^&*()_+"

    if len(update.command) > 1:
        limit = int(update.command[1])
    else:
        limit = random.choice([5, 6, 7, 8, 9, 10, 12, 14])

    password = "".join(random.sample(chars, limit))
    PASSWORD_CACHE[update.from_user.id] = password

    txt = (
        f"<b>Password Length:</b> {limit}\n"
        f"<b>Password:</b> <code>{password}</code>\n\n"
        f"🔐 <i>Generated by @kira_probot</i>"
    )

    btn = InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    "📋 Copy Password", callback_data="copy_password"
                )
            ],
            [
                InlineKeyboardButton(
                    "➕ ADD ME IN YOUR GROUP",
                    url="https://t.me/kira_probot?startgroup=true",
                )
            ],
        ]
    )

    await message.edit_text(
        txt, reply_markup=btn, parse_mode=enums.ParseMode.HTML
    )


@app.on_callback_query(filters.regex("^copy_password$"))
async def copy_password(_, query):
    pwd = PASSWORD_CACHE.get(query.from_user.id)
    if not pwd:
        return await query.answer(
            "❌ Password expired. Generate a new one.",
            show_alert=True,
        )

    await query.answer(
        f"Password:\n{pwd}\n\nTap & hold to copy ✅",
        show_alert=True,
    )
